# Generated by Django 4.1.2 on 2022-10-21 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gsm', '0002_remove_signal_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topsearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter', models.IntegerField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gsm.location')),
            ],
        ),
    ]
