# Generated by Django 4.1.2 on 2022-11-23 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gsm', '0004_remove_signal_indicator'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Indicators',
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name_plural': 'Locations'},
        ),
        migrations.AlterModelOptions(
            name='network',
            options={'verbose_name_plural': 'Networks'},
        ),
        migrations.AlterModelOptions(
            name='signal',
            options={'verbose_name_plural': 'Signals'},
        ),
        migrations.AlterModelOptions(
            name='topsearch',
            options={'verbose_name_plural': 'Topsearches'},
        ),
    ]
